// import { Gender, User } from './user'

// export const USERS: User[] = [
//   {
//     _id: 11,
//     firstname: 'Dr Mighty',
//     lastname: 'Fine',
//     password: 'password',
//     email: 'Nice@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 12,
//     firstname: 'Narco',
//     lastname: 'Cic',
//     password: 'password',
//     email: 'Narco@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 13,
//     firstname: 'Bombasto',
//     lastname: 'Manfred',
//     password: 'password',
//     email: 'Bombasto@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 14,
//     firstname: 'Celeritas',
//     lastname: 'Bullet',
//     password: 'password',
//     email: 'Celeritas@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 15,
//     firstname: 'Magneta',
//     lastname: 'Men',
//     password: 'password',
//     email: 'Magneta@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 16,
//     firstname: 'RubberMan',
//     lastname: 'Elastic',
//     password: 'password',
//     email: 'RubberMan@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 17,
//     firstname: 'Dynama',
//     lastname: 'Danger',
//     password: 'password',
//     email: 'Dynama@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 18,
//     firstname: 'Dr IQ',
//     lastname: 'Smart',
//     password: 'password',
//     email: 'IQ@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 19,
//     firstname: 'Magma',
//     lastname: 'Trail',
//     password: 'password',
//     email: 'Magma@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   },
//   {
//     _id: 20,
//     firstname: 'Tornado',
//     lastname: 'Danger',
//     password: 'password',
//     email: 'Tornado@gmail.com',
//     phonenumber: '06-44556666',
//     birthdate: new Date('12-04-1982'),
//     gender: Gender.Male,
//   }
// ]
